import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Home,PenLine,ReceiptText,ChartNoAxesCombined,Lightbulb,Settings,Bell,ChevronDown,Plus,Utensils,ShoppingBag,GraduationCap,Bus,Gamepad2,WalletCards,X,CalendarDays,Check,Leaf}from'lucide-react';
import{ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell}from'recharts';
import'./styles.css';

const categories=[
 {name:'椁愰ギ',color:'#ff9f43',icon:Utensils},{name:'鏃ョ敤鍝?,color:'#56c987',icon:ShoppingBag},{name:'瀛﹁垂/鏁欒偛',color:'#4d9cf5',icon:GraduationCap},{name:'浜ら€?,color:'#8b72f6',icon:Bus},{name:'濞变箰',color:'#fb7185',icon:Gamepad2},{name:'鍏朵粬',color:'#aab3be',icon:WalletCards}
];
const seed=[
 {id:1,date:'2026-08-11',category:'椁愰ギ',type:'鏀嚭',amount:28,note:'椋熷爞鍗堥'},
 {id:2,date:'2026-08-11',category:'鏃ョ敤鍝?,type:'鏀嚭',amount:15.8,note:'绾稿肪銆佹礂琛ｆ恫'},
 {id:3,date:'2026-08-10',category:'瀛﹁垂/鏁欒偛',type:'鏀嚭',amount:399,note:'鑻辫缃戣'},
 {id:4,date:'2026-08-09',category:'浜ら€?,type:'鏀嚭',amount:6,note:'鍦伴搧鍑鸿'},
 {id:5,date:'2026-08-08',category:'鍏朵粬',type:'鏀跺叆',amount:500,note:'瀹舵暀鍏艰亴'},
 {id:6,date:'2026-08-07',category:'濞变箰',type:'鏀嚭',amount:64,note:'鍛ㄦ湯鐢靛奖'},
 {id:7,date:'2026-08-06',category:'椁愰ギ',type:'鏀嚭',amount:35,note:'鏈嬪弸鑱氶'},
];
const trend=[9,15,12,20,7,18,11,25,16,8,22].map((v,i)=>({day:`8/${i+1}`,amount:v*8+(i===8?120:0)}));
const money=n=>`楼 ${n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

function Sidebar({active,setActive,onAdd}){const items=[[Home,'姒傝'],[PenLine,'璁颁竴绗?],[ReceiptText,'璐﹀崟'],[ChartNoAxesCombined,'缁熻鎶ュ憡'],[Lightbulb,'鐞嗚储寤鸿']];return <aside className="sidebar"><div className="brand"><span className="brandmark"><Leaf/></span>闈掔璐︽湰</div><nav>{items.map(([Icon,label])=><button key={label} className={active===label?'active':''} onClick={()=>label==='璁颁竴绗??onAdd():setActive(label)}><Icon/>{label}</button>)}</nav><div className="growth"><div className="plant">馃尡</div><strong>姣忎竴绗旇褰?br/>閮芥槸鎴愰暱鐨勭Н绱?/strong><p>鏈湀宸茶璐?11 澶?/p><div className="progress"><i/></div><small>11 / 31 澶?/small></div><button className="settings"><Settings/>璁剧疆</button></aside>}
function Metric({kind,label,value,change}){return <div className={`metric ${kind}`}><span className="metric-icon">{kind==='balance'?<WalletCards/>:kind==='income'?'鈫?:'鈫?}</span><div><p>{label}</p><strong>{money(value)}</strong><small>杈冧笂鏈?<em>{change}</em></small></div></div>}
function TrendChart({transactions,view,setView}){const data=useMemo(()=>trend.map(d=>({...d,amount:d.amount+transactions.filter(t=>t.type==='鏀嚭'&&Number(t.date.slice(-2))===Number(d.day.split('/')[1])).reduce((s,t)=>s+t.amount,0)})),[transactions]);return <section className="panel chart-panel"><header><h2>鏀嚭瓒嬪娍</h2><div className="switch"><button className={view==='鏃??'on':''} onClick={()=>setView('鏃?)}>鏃?/button><button className={view==='鏈??'on':''} onClick={()=>setView('鏈?)}>鏈?/button></div></header><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:16,right:8,left:-22,bottom:0}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#20b26b" stopOpacity=".28"/><stop offset="1" stopColor="#20b26b" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf0ee" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)} contentStyle={{border:'1px solid #e7ece9',borderRadius:12,boxShadow:'0 8px 30px #1d3b2d18'}}/><Area type="monotone" dataKey="amount" stroke="#10a75f" strokeWidth={3} fill="url(#fill)" activeDot={{r:5}}/></AreaChart></ResponsiveContainer></div></section>}
function Breakdown({transactions}){const data=categories.map(c=>({...c,value:transactions.filter(t=>t.type==='鏀嚭'&&t.category===c.name).reduce((s,t)=>s+t.amount,0)})).filter(d=>d.value);const total=data.reduce((s,d)=>s+d.value,0);return <section className="panel breakdown"><header><h2>鍒嗙被鍗犳瘮</h2><button className="link">鏌ョ湅璇︽儏 鈥?/button></header><div className="pie"><ResponsiveContainer width="52%" height={210}><PieChart><Pie data={data} dataKey="value" innerRadius={60} outerRadius={88} paddingAngle={2} stroke="none">{data.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="pie-center"><small>鎬绘敮鍑?/small><strong>{money(total)}</strong></div><div className="legend">{data.map(d=><div key={d.name}><i style={{background:d.color}}/><span>{d.name}</span><b>{total?Math.round(d.value/total*100):0}%</b></div>)}</div></div></section>}
function Transactions({items,onAdd}){return <section className="panel transactions"><header><h2>鏈€杩戣处鍗?/h2><button className="link">鏌ョ湅鍏ㄩ儴 鈥?/button></header><div className="table-head"><span>鏃ユ湡</span><span>鍒嗙被</span><span>鏀舵敮</span><span>閲戦</span><span>澶囨敞</span></div>{items.slice(0,5).map(t=>{const c=categories.find(x=>x.name===t.category)||categories[5];const Icon=c.icon;return <div className="transaction" key={t.id}><span>{t.date.slice(5).replace('-','/')}</span><span className="cat"><i style={{background:c.color}}><Icon/></i>{t.category}</span><span className={t.type==='鏀跺叆'?'positive':'negative'}>{t.type}</span><strong className={t.type==='鏀跺叆'?'positive':'negative'}>{t.type==='鏀跺叆'?'+':'-'} {money(t.amount)}</strong><span>{t.note||'鈥?}</span></div>})}<button className="add-bottom" onClick={onAdd}><PenLine/>璁颁竴绗?/button></section>}
function Advice({expense}){return <section className="panel advice"><header><h2>浠婃棩寤鸿</h2><span className="advice-plant">馃尶</span></header><div><Utensils/><strong>鎺у埗椁愰ギ鏀嚭</strong></div><p>浣犱粖鏃ラ楗敮鍑哄崰姣旇緝楂橈紝寤鸿閫傚綋鎺у埗锛岃嚜宸卞仛楗洿鍋ュ悍鍙堢渷閽卞摝锛?/p><b>鏈湀椁愰ギ鏀嚭鍗?27%</b><div className="goal"><i/><span>寤鸿 鈮?30%</span></div><ul><li><Check/>鎻愬墠瑙勫垝涓夐锛屽噺灏戝啿鍔ㄦ秷璐?/li><li><Check/>澶氬埄鐢ㄦ牎鍥鍫傦紝鎬т环姣旀洿楂?/li><li><Check/>姣忓懆璁惧畾棰勭畻锛屼繚鎸佸ソ涔犳儻</li></ul></section>}
function AddDrawer({open,onClose,onSave}){const [form,setForm]=useState({type:'鏀嚭',amount:'',category:'椁愰ギ',date:'2026-08-11',note:''});const submit=e=>{e.preventDefault();if(!Number(form.amount))return;onSave({...form,amount:Number(form.amount),id:Date.now()});setForm({...form,amount:'',note:''});};return <><div className={`backdrop ${open?'show':''}`} onClick={onClose}/><aside className={`drawer ${open?'open':''}`}><header><h2>璁颁竴绗?/h2><button onClick={onClose}><X/></button></header><form onSubmit={submit}><div className="type-tabs"><button type="button" className={form.type==='鏀嚭'?'selected expense':''} onClick={()=>setForm({...form,type:'鏀嚭'})}>鏀嚭</button><button type="button" className={form.type==='鏀跺叆'?'selected':''} onClick={()=>setForm({...form,type:'鏀跺叆'})}>鏀跺叆</button></div><label>閲戦<div className="amount-input"><span>楼</span><input autoFocus inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00"/></div></label><label>鍒嗙被<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>鏃ユ湡<div className="date-input"><CalendarDays/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div></label><label>澶囨敞<textarea maxLength="50" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="璇疯緭鍏ュ娉紙閫夊～锛?/><small>{form.note.length} / 50</small></label><button className="save">淇濆瓨</button><button type="button" className="cancel" onClick={onClose}>鍙栨秷</button></form></aside></>}
function App(){const[active,setActive]=useState('姒傝');const[open,setOpen]=useState(false);const[view,setView]=useState('鏃?);const[transactions,setTransactions]=useState(seed);const income=transactions.filter(t=>t.type==='鏀跺叆').reduce((s,t)=>s+t.amount,0)+2700;const expense=transactions.filter(t=>t.type==='鏀嚭').reduce((s,t)=>s+t.amount,0)+1386.4;const save=t=>{setTransactions([t,...transactions]);setOpen(false)};return <div className="app"><Sidebar active={active} setActive={setActive} onAdd={()=>setOpen(true)}/><main><header className="topbar"><div><h1>浣犲ソ锛屽闇稿悓瀛?馃憢</h1><p>娆㈣繋鍥炴潵锛屼粖澶╀篃鏄鐪熻璐︾殑涓€澶╋紒</p></div><div className="profile"><button><Bell/><i/></button><span>馃懆馃徎鈥嶐煄?/span><b>瀛﹂湼鍚屽</b><ChevronDown/></div></header><div className="metrics"><Metric kind="balance" label="鏈湀缁撲綑" value={income-expense} change="+18.6%"/><Metric kind="income" label="鏈湀鏀跺叆" value={income} change="+12.3%"/><Metric kind="expense" label="鏈湀鏀嚭" value={expense} change="+8.7%"/></div><div className="grid"><TrendChart transactions={transactions} view={view} setView={setView}/><Breakdown transactions={transactions}/><Transactions items={transactions} onAdd={()=>setOpen(true)}/><Advice expense={expense}/></div></main><button className="mobile-add" onClick={()=>setOpen(true)}><Plus/></button><AddDrawer open={open} onClose={()=>setOpen(false)} onSave={save}/></div>}
createRoot(document.getElementById('root')).render(<App/>);
